Report daemon OOM better
When copying a large path causes the daemon to run out of memory, you
now get:

  error: Nix daemon out of memory

instead of:

  error: writing to file: Broken pipe


Former-commit-id: b1beed97a0670befbfd5e105a81132e87e58ac37