Rename nul.nar because nul is a special name in Windows
For example, we can't even clone the repository on Windows!

    error: invalid path 'tests/functional/nul.nar'
    fatal: unable to checkout working tree


Former-commit-id: 190d0d661e3c00b932b4dba0359fedb218d70c3c