Print a more helpful message if the daemon crashes
Instead of

   error: unexpected end-of-file

you now get

   error: Nix daemon disconnected unexpectedly (maybe it crashed?)


Former-commit-id: a3cf27ca47328b11173147ca7180e0bae798bb2c