Restore an accidentally suppressed negation
Accidentally removed in 9e7fe5625f7409b6527d303a1f13a22f49d27377 [formerly ca96f5219489c1002499bfe2c580fdd458219144]. This
caused `nix run` to systematically fail with

```
error: app program '/nix/store/…' is not in the Nix store
```

Former-commit-id: 59d0de6ea17b7836e7f2e169ea4c8e65b413500a