libfetchers/github: allow `url` attribute
Since cdd516d4fc38eed17744a933d971095bc5c69533 [formerly 108debef6f703aa3ca1f6d6c45428880624ec6f8] we allow a
`url`-attribute for the `github`-fetcher to fetch tarballs from
self-hosted `gitlab`/`github` instances.

However it's not used when defining e.g. a flake-input

    foobar = {
        type = "github";
        url = "gitlab.myserver";
        /* ... */
    }

and breaks with an evaluation-error:

    error: --- Error --------------------------------------nix
    unsupported input attribute 'url'
    (use '--show-trace' to show detailed location information)

This patch allows flake-inputs to be fetched from self-hosted instances
as well.


Former-commit-id: 2bcf8cbe7a36ebcd2ad27b4df18fdb911d7ab224