nix flake {metadata,archive}: Fix chroot stores
Fixes

  $ nix flake metadata --store /tmp/nix nixpkgs
  error: path '/tmp/nix/nix/store/65xpqkz92d9j7k5ric4z8lzhiigxsfbg-source/flake.nix' is not in the Nix store

This has been broken since d76c443019218a746ff131b089a6d8b448898da9 [formerly 598deb2b23bc59df61c92ea25745d675686f3991].


Former-commit-id: c5a4dfa6602796ebb3c62493a2fd33f2b58ec91c