Add test for indirect flake dependencies
I.e. flake3 depends on flake2 which depends on flake1. Currently this
fails with

  error: indirect flake reference 'flake1' is not allowed

because we're not propagating lockfiles downwards properly.


Former-commit-id: 391e1f511d90461dcdd52e495e2596bbd2ea3c5a