Revert "don't abort when given unmatched '}' with 'start-condition stack underflow'. This fixes  #751"
This reverts commit 19d37575ea76e645a82d234819645096895e3d4e [formerly 8d22b26448a091c76ab972c0b0603daac5e255e4]. It
breaks Nixpkgs:

$ nix-env -qa
error: syntax error, unexpected IND_STR, expecting '}', at /home/eelco/Dev/nixpkgs-stable/pkgs/top-level/python-packages.nix:7605:8

Former-commit-id: 8120b6fb8a4924f8ae717bba9bbda4a2f89e2141