Revert "remove obsolete stdenv darwinMinVersion override"
This reverts commit 602ac7b38420a413ba7d6de216804f8ac30d3baa [formerly d91310bb32b9efca2f1e1a6a767cbe5b0a7f072c].

> Some packages require setting a non-default deployment target
> (or minimum version) to gain access to certain APIs. You do
> that using the darwinMinVersionHook, which takes the deployment
> target version as a parameter.

-- https://github.com/NixOS/nixpkgs/blob/60b54c7aee3c0cefde72d1a151bb7d3a46361ca2/doc/stdenv/platform-notes.chapter.md#what-is-a-deployment-target-or-minimum-version-sec-darwin-troubleshooting-using-deployment-targets

This will again solve error:

    ../nix_api_expr.cc:38:18: error: aligned allocation function of type 'void *(std::size_t, std::align_val_t)' is only available on macOS 10.13 or newer

-- https://hydra.nixos.org/build/294088946


Former-commit-id: 5c4a4aeed7aeb808b5c3c6edc89b8f35d640f40b